# Generated by Django 4.2.29 on 2026-04-22 05:36

from datetime import date, timedelta
import random

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from main.models import Expense
from django.contrib.auth.models import User


start_date = date(2026, 3, 1)
end_date = date.today()


def seed_transactions(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')

    user = User.objects.order_by('id').first()
    if user is None:
        user = User.objects.create_user(
            username='admin',
            password='admin',
        )

    if Expense.objects.exists():
        return

    descriptions = {
        'food': ['Lunch at restaurant', 'Coffee', 'Dinner', 'Snacks', 'Fast food'],
        'transport': ['Bus ticket', 'Taxi', 'Uber', 'Train ticket', 'Gas'],
        'groceries': ['Weekly groceries', 'Milk and bread', 'Vegetables', 'Fruits'],
        'bills': ['Electricity bill', 'Water bill', 'Internet bill', 'Phone bill'],
        'entertainment': ['Movie ticket', 'Concert', 'Books', 'Games']
    }

    expenses = []
    current_date = start_date
    while current_date <= end_date:
        num_expenses = random.choice([0, 0, 0, 1, 1, 2, 3])  # Favor fewer expenses
        for _ in range(num_expenses):
            category = random.choice(['food', 'transport', 'groceries', 'bills', 'entertainment'])
            amount = round(random.uniform(5, 200), 2)
            description = random.choice(descriptions[category])
            expenses.append(Expense(
                amount=str(amount),
                category=category,
                description=description,
                date=current_date,
                user=user
            ))
        current_date += timedelta(days=1)

    print(expenses)
    Expense.objects.bulk_create(expenses)


def unseed_transactions(apps, schema_editor):
    Expense = apps.get_model('main', 'Expense')
    Expense.objects.filter(date__gte=start_date, date__lte=end_date).delete()

class Migration(migrations.Migration):

    initial = True

    today = date.today()

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('groceries', 'Groceries'), ('bills', 'Bills'), ('entertainment', 'Entertainment')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_transactions, unseed_transactions),
    ]